Proyecto_Ruby/opticScience/config/routes.rb
OpticScience::Application.routes.draw do
  resources :client
	resources :item

end

Proyecto_Ruby/opticScience/app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :venta
end

Proyecto_Ruby/opticScience/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :venta
end

Proyecto_Ruby/opticScience/app/models/venta.rb
class Venta < ActiveRecord::Base
	has_one :item
	has_one :client
end

Proyecto_Ruby/opticScience/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Proyecto_Ruby/opticScience/app/controllers/client_controller.rb
class ClientController < ApplicationController

  def index
    @clients = Client.all
		@items = Item.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params.require(:client).permit(:cedula, :nombre, :apellido))
    if @client.save
      redirect_to client_index_path, :notice => "Se registro correctamente"
    else
      render :action => "new"
    end
  end
  
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to client_index_path, :notice => "Se ah eliminado correctamente"
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(params.require(:client).permit(:cedula, :nombre, :apellido))
      redirect_to client_index_path, :notice => "Se actualizo correctamente"
    else
      render "edit"
    end
  end
end

Proyecto_Ruby/opticScience/app/controllers/item_controller.rb
class ItemController < ApplicationController
def index
    @clients = Client.all
		@items = Item.all
  end

  def new
		@item = Item.new
  end

  def create
		@item = Item.new(params.require(:item).permit(:nombre,:valor))
    if @item.save
      redirect_to client_index_path, :notice => "Se registro correctamente"
    else
      render :action => "new"
    end
  end
  
  def destroy
		@item = Item.find(params[:id])
    @item.destroy
    redirect_to client_index_path, :notice => "Se ah eliminado correctamente"
  end

  def edit
		@item = Item.find(params[:id])
  end

  def update
		@item = Item.find(params[:id])
    if @item.update_attributes(params.require(:item).permit(:nombre,:valor))
      redirect_to client_index_path, :notice => "Se actualizo correctamente"
    else
      render "edit"
    end
  end
end

Proyecto_Ruby/opticScience/app/controllers/venta_controller.rb
class VentaController < ApplicationController
	def index
  end

  def new
		@venta = Venta.new
  end

  def create
		@venta = Venta.new(params.require(:venta).permit(:@client.cedula,:@item.nombre,@item.valor,:localidad))
    if @item.save
      redirect_to client_index_path, :notice => "Se registro correctamente"
    else
      render :action => "new"
    end
  end
  
  def destroy
		@item = Item.find(params[:id])
    @item.destroy
    redirect_to client_index_path, :notice => "Se ah eliminado correctamente"
  end

  def edit
		@item = Item.find(params[:id])
  end

  def update
		@item = Item.find(params[:id])
    if @item.update_attributes(params.require(:item).permit(:nombre,:valor))
      redirect_to client_index_path, :notice => "Se actualizo correctamente"
    else
      render "edit"
    end
  end
end

Proyecto_Ruby/opticScience/app/helpers/application_helper.rb
module ApplicationHelper
end

Proyecto_Ruby/opticScience/app/helpers/client_helper.rb
module ClientHelper
end

Proyecto_Ruby/opticScience/app/helpers/item_helper.rb
module ItemHelper
end

Proyecto_Ruby/opticScience/app/helpers/venta_helper.rb
module VentaHelper
end

Proyecto_Ruby/opticScience/app/views/client/edit.html.erb
<h1>Editar cliente</h1>

<%= form_for @client,:url => { :action => "update" } do |f| %>﻿
  <p>
    <%= f.label :cedula %>: <%= f.text_field :cedula %><br /><br />
    <%= f.label :nombre %>: <%= f.text_field :nombre %><br /><br />
    <%= f.label :apellido %>: <%= f.text_field :apellido %><br />
  </p>
  <p>
    <%= f.submit "Actualizar cliente"%>
  </p>
<%end%>

Proyecto_Ruby/opticScience/app/views/client/index.html.erb
<h1>OpticScience</h1>
<p>Bienvenidos a nuestra base de datos!</p>
<hr />
<p><h2>Listado de clientes registrados</h2> </p>
<hr />
<p><%=link_to "Agregar nuevo cliente", new_client_path%></p>
<p><b>Cedula  |  Nombre  |  Apellido</b></p>
<% @clients.each do |client| %>
  <p><%= client.cedula %> | <%= client.nombre %> <%= client.apellido %> [<%= link_to "Editar", edit_client_path(client) %> | <%= link_to "Eliminar", client, :confirm => "Estas seguro?", :method => :delete %>]</p>
<% end %>
<hr />
<p><h2>Listado de items registrados</h2></p>
<hr />
<p><%=link_to "Agregar nuevo item", new_item_path%></p>
<p><b>Nombre  |  Valor  </b></p>
<% @items.each do |item| %>
  <p><%= item.nombre %> | <%= item.valor %> [<%= link_to "Editar", edit_item_path(item) %> | <%= link_to "Eliminar", item, :confirm => "Estas seguro?", :method => :delete %>] </p>
<% end %>

Proyecto_Ruby/opticScience/app/views/client/new.html.erb
<h1>Nuevo cliente</h1>

<%= form_for @client,:url => { :action => "create" } do |f| %>﻿
  <p>
    <%= f.label :cedula %>: <%= f.text_field :cedula %><br /><br />
    <%= f.label :nombre %>: <%= f.text_field :nombre %><br /><br />
    <%= f.label :apellido %>: <%= f.text_field :apellido %><br />
  </p>
  <p>
    <%= f.submit "Registrar nuevo cliente"%>
  </p>
<%end%>

Proyecto_Ruby/opticScience/app/views/item/edit.html.erb
<h1>Editar item</h1>

<%= form_for @item,:url => { :action => "update" } do |f| %>﻿
  <p>
    <%= f.label :nombre %>: <%= f.text_field :nombre %><br /><br />
    <%= f.label :valor %>: <%= f.text_field :valor %><br />
  </p>
  <p>
    <%= f.submit "Actualizar item"%>
  </p>
<%end%>

Proyecto_Ruby/opticScience/app/views/item/new.html.erb
<h1>Nuevo item</h1>

<%= form_for @item,:url => { :action => "create" } do |f| %>﻿
  <p>
    <%= f.label :nombre %>: <%= f.text_field :nombre %><br /><br />
    <%= f.label :valor %>: <%= f.text_field :valor %><br />
  </p>
  <p>
    <%= f.submit "Registrar nuevo item"%>
  </p>
<%end%>

Proyecto_Ruby/opticScience/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpticScience</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key,value| %>
  <p><%= value %></p>
<%end%>
<%= yield %>

</body>
</html>